data = {

    'Adjust the wave modifier': '调整波修改器',
    'WaveHelper': '波修改器',
    'Motion': '运动',
    'Along Normals': '沿法向',
    'Falloff': '衰减',
    'Vertex Groups': '顶点组',
    'Animation': '动画',
    'Total frame count for looping': '循环总帧数',
    'Total frame count for motion': '运动总帧数',
    'Frame Start': '起始帧',
    'Frame Zero': '归零帧',
    'Frame End': '结束帧',
    'Frame Stop': '停止帧',
    'Full stop frame': '完全停止帧',
    'Damping': '阻尼',
    'Offset': '偏移量',
    'Set loop animation': '设置循环动画',
    'Width': '波宽度',
    'Width of each wave': '每个波的宽度',
    'High precision': '高精度',
    'Wave spacing': '波间隔',
    'The spacing between each wave': '每个波之间的间隔',
    'Frequency': '频率',
    'In one second, the number of oscillations of particles, directly expressed as the reciprocal of the period': '一秒内，粒子的振动次数，直接表示为周期的倒数',
    'Direction': '方向',
    'Diffusion': '扩散',
    'Shrink': '收缩',

}
